import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1768223087294 implements MigrationInterface {
  name = "InitialSchema1768223087294";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TABLE \"reservation\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"tableId\" varchar NOT NULL, \"customerName\" varchar NOT NULL, \"customerPhone\" varchar NOT NULL, \"partySize\" integer NOT NULL, \"reservationDate\" date NOT NULL, \"reservationStartTime\" time NOT NULL, \"reservationEndTime\" time NOT NULL, \"duration\" integer NOT NULL, \"status\" varchar CHECK( \"status\" IN ('pending','confirmed','completed','cancelled') ) NOT NULL DEFAULT ('confirmed'), \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("CREATE TABLE \"table\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"tableNumber\" integer NOT NULL, \"capacity\" integer NOT NULL, \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("CREATE TABLE \"waitlist\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"customerName\" varchar NOT NULL, \"customerPhone\" varchar NOT NULL, \"partySize\" integer NOT NULL, \"requestedDate\" date NOT NULL, \"requestedTime\" time NOT NULL, \"preferredTimeRange\" varchar, \"status\" varchar CHECK( \"status\" IN ('waiting','notified','expired') ) NOT NULL DEFAULT ('waiting'), \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("CREATE TABLE \"restaurant\" (\"id\" varchar PRIMARY KEY NOT NULL, \"name\" varchar NOT NULL, \"openingTime\" varchar NOT NULL, \"closingTime\" varchar NOT NULL, \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("CREATE TABLE \"temporary_reservation\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"tableId\" varchar NOT NULL, \"customerName\" varchar NOT NULL, \"customerPhone\" varchar NOT NULL, \"partySize\" integer NOT NULL, \"reservationDate\" date NOT NULL, \"reservationStartTime\" time NOT NULL, \"reservationEndTime\" time NOT NULL, \"duration\" integer NOT NULL, \"status\" varchar CHECK( \"status\" IN ('pending','confirmed','completed','cancelled') ) NOT NULL DEFAULT ('confirmed'), \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT \"FK_2a2d6c09d1469e65c347513256a\" FOREIGN KEY (\"restaurantId\") REFERENCES \"restaurant\" (\"id\") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT \"FK_d221f3398a0352970306b3dc676\" FOREIGN KEY (\"tableId\") REFERENCES \"table\" (\"id\") ON DELETE CASCADE ON UPDATE NO ACTION)");
    await queryRunner.query("INSERT INTO \"temporary_reservation\"(\"id\", \"restaurantId\", \"tableId\", \"customerName\", \"customerPhone\", \"partySize\", \"reservationDate\", \"reservationStartTime\", \"reservationEndTime\", \"duration\", \"status\", \"createdAt\", \"updatedAt\") SELECT \"id\", \"restaurantId\", \"tableId\", \"customerName\", \"customerPhone\", \"partySize\", \"reservationDate\", \"reservationStartTime\", \"reservationEndTime\", \"duration\", \"status\", \"createdAt\", \"updatedAt\" FROM \"reservation\"");
    await queryRunner.query("DROP TABLE \"reservation\"");
    await queryRunner.query("ALTER TABLE \"temporary_reservation\" RENAME TO \"reservation\"");
    await queryRunner.query("CREATE TABLE \"temporary_table\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"tableNumber\" integer NOT NULL, \"capacity\" integer NOT NULL, \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT \"FK_bfbf9c025448272dc0453bf8f55\" FOREIGN KEY (\"restaurantId\") REFERENCES \"restaurant\" (\"id\") ON DELETE CASCADE ON UPDATE NO ACTION)");
    await queryRunner.query("INSERT INTO \"temporary_table\"(\"id\", \"restaurantId\", \"tableNumber\", \"capacity\", \"createdAt\", \"updatedAt\") SELECT \"id\", \"restaurantId\", \"tableNumber\", \"capacity\", \"createdAt\", \"updatedAt\" FROM \"table\"");
    await queryRunner.query("DROP TABLE \"table\"");
    await queryRunner.query("ALTER TABLE \"temporary_table\" RENAME TO \"table\"");
    await queryRunner.query("CREATE TABLE \"temporary_waitlist\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"customerName\" varchar NOT NULL, \"customerPhone\" varchar NOT NULL, \"partySize\" integer NOT NULL, \"requestedDate\" date NOT NULL, \"requestedTime\" time NOT NULL, \"preferredTimeRange\" varchar, \"status\" varchar CHECK( \"status\" IN ('waiting','notified','expired') ) NOT NULL DEFAULT ('waiting'), \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT \"FK_d866abc87f84123e7ed47cdfee2\" FOREIGN KEY (\"restaurantId\") REFERENCES \"restaurant\" (\"id\") ON DELETE CASCADE ON UPDATE NO ACTION)");
    await queryRunner.query("INSERT INTO \"temporary_waitlist\"(\"id\", \"restaurantId\", \"customerName\", \"customerPhone\", \"partySize\", \"requestedDate\", \"requestedTime\", \"preferredTimeRange\", \"status\", \"createdAt\", \"updatedAt\") SELECT \"id\", \"restaurantId\", \"customerName\", \"customerPhone\", \"partySize\", \"requestedDate\", \"requestedTime\", \"preferredTimeRange\", \"status\", \"createdAt\", \"updatedAt\" FROM \"waitlist\"");
    await queryRunner.query("DROP TABLE \"waitlist\"");
    await queryRunner.query("ALTER TABLE \"temporary_waitlist\" RENAME TO \"waitlist\"");
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("ALTER TABLE \"waitlist\" RENAME TO \"temporary_waitlist\"");
    await queryRunner.query("CREATE TABLE \"waitlist\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"customerName\" varchar NOT NULL, \"customerPhone\" varchar NOT NULL, \"partySize\" integer NOT NULL, \"requestedDate\" date NOT NULL, \"requestedTime\" time NOT NULL, \"preferredTimeRange\" varchar, \"status\" varchar CHECK( \"status\" IN ('waiting','notified','expired') ) NOT NULL DEFAULT ('waiting'), \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("INSERT INTO \"waitlist\"(\"id\", \"restaurantId\", \"customerName\", \"customerPhone\", \"partySize\", \"requestedDate\", \"requestedTime\", \"preferredTimeRange\", \"status\", \"createdAt\", \"updatedAt\") SELECT \"id\", \"restaurantId\", \"customerName\", \"customerPhone\", \"partySize\", \"requestedDate\", \"requestedTime\", \"preferredTimeRange\", \"status\", \"createdAt\", \"updatedAt\" FROM \"temporary_waitlist\"");
    await queryRunner.query("DROP TABLE \"temporary_waitlist\"");
    await queryRunner.query("ALTER TABLE \"table\" RENAME TO \"temporary_table\"");
    await queryRunner.query("CREATE TABLE \"table\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"tableNumber\" integer NOT NULL, \"capacity\" integer NOT NULL, \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("INSERT INTO \"table\"(\"id\", \"restaurantId\", \"tableNumber\", \"capacity\", \"createdAt\", \"updatedAt\") SELECT \"id\", \"restaurantId\", \"tableNumber\", \"capacity\", \"createdAt\", \"updatedAt\" FROM \"temporary_table\"");
    await queryRunner.query("DROP TABLE \"temporary_table\"");
    await queryRunner.query("ALTER TABLE \"reservation\" RENAME TO \"temporary_reservation\"");
    await queryRunner.query("CREATE TABLE \"reservation\" (\"id\" varchar PRIMARY KEY NOT NULL, \"restaurantId\" varchar NOT NULL, \"tableId\" varchar NOT NULL, \"customerName\" varchar NOT NULL, \"customerPhone\" varchar NOT NULL, \"partySize\" integer NOT NULL, \"reservationDate\" date NOT NULL, \"reservationStartTime\" time NOT NULL, \"reservationEndTime\" time NOT NULL, \"duration\" integer NOT NULL, \"status\" varchar CHECK( \"status\" IN ('pending','confirmed','completed','cancelled') ) NOT NULL DEFAULT ('confirmed'), \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
    await queryRunner.query("INSERT INTO \"reservation\"(\"id\", \"restaurantId\", \"tableId\", \"customerName\", \"customerPhone\", \"partySize\", \"reservationDate\", \"reservationStartTime\", \"reservationEndTime\", \"duration\", \"status\", \"createdAt\", \"updatedAt\") SELECT \"id\", \"restaurantId\", \"tableId\", \"customerName\", \"customerPhone\", \"partySize\", \"reservationDate\", \"reservationStartTime\", \"reservationEndTime\", \"duration\", \"status\", \"createdAt\", \"updatedAt\" FROM \"temporary_reservation\"");
    await queryRunner.query("DROP TABLE \"temporary_reservation\"");
    await queryRunner.query("DROP TABLE \"restaurant\"");
    await queryRunner.query("DROP TABLE \"waitlist\"");
    await queryRunner.query("DROP TABLE \"table\"");
    await queryRunner.query("DROP TABLE \"reservation\"");
  }

}
